### ISSUE TITLE
йода синтаксис плохо влияет на читаемость кода

### ISSUE THREAD

**Issue by dyaroman** [mpodanev/lm-screenshoter#11]
в прошлый раз это пропустил
я понимаю что ты это из примера взял
но так как ты не йода
думаю стоит написать нормально

https://github.com/mpodanev/lm-screenshoter/blob/d505c32958ceaf41f2d670d71e937cc2c766f371/index.js#L42

**Comment by mpodaniev** [comment]
Мне тоже не нравится и тоже хотел заменить :)
Сделаю

**Comment by dyaroman** [comment]
good job
