### ISSUE TITLE
интерактивный режим

### ISSUE THREAD

**Issue by dyaroman** [mpodanev/lm-screenshoter#4]
изучить возможность использования интерактивного режима работы, по аналогии с `ng new`
чтобы была возможность передавать необходимые параметры, отвечая на вопросы в командной строке

**Comment by mpodaniev** [comment]
Выбор пал на два пакета: [раз](https://www.npmjs.com/package/enquirer) и [два](https://www.npmjs.com/package/prompts)
Первый на основе второго сделан, но там больше красившостей.
@dyaroman если можешь посмотри их, завтра буду реализовывать

**Comment by dyaroman** [comment]
оба пакета выглядят хорошо, но у [prompts](https://www.npmjs.com/package/prompts) в разы больше скачиваний, давай начнем с него

**Comment by mpodaniev** [comment]
Ok

**Comment by dyaroman** [comment]
great job!
